domain: zoyafuso-noaa.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://zoyafuso-noaa.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /AIGOA_Core_Otolith/         # place folder name if the site is served in a subfolder